promesas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("promise_tracker.urls")),
]

urlpatterns += staticfiles_urlpatterns()

promise_tracker/urls.py
from django.urls import path, include

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


# user login patters
urlpatterns = [
    path("", views.index, name="index"),
    # path('', views.PromiseListView.as_view(), name='index'),
    path('promises/', views.PromiseListView.as_view(), name='promises'),
    path('user/promises', login_required(views.PromiseListView.as_view()), name='promises_user'),
    path('promises/<int:pk>/detail', views.PromiseDetailView.as_view(), name='promise_detail'),
    path('promises/create/', login_required(views.PromiseCreateView.as_view()), name='promise_create'),
    path('promises/<int:pk>/update/', login_required(views.PromiseUpdateView.as_view()), name='promise_update'),
    path('promises/<int:pk>/delete/', login_required(views.PromiseDeleteView.as_view()), name='promise_delete'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    # positions
    # path('', views.PositionListView.as_view(), name='all'),
    path('positions/', views.PositionListView.as_view(), name='positions'),
    path('positions/<int:pk>/detail', views.PositionDetailView.as_view(), name='position_detail'),
    path('positions/create/', login_required(views.PositionCreateView.as_view()), name='position_create'),
    path('positions/<int:pk>/update/',login_required(views.PositionUpdateView.as_view()), name='position_update'),
    path('positions/<int:pk>/delete/',login_required(views.PositionDeleteView.as_view()), name='position_delete'),
     #parties
     path('parties/', views.PartyListView.as_view(), name='parties'),
    path('parties/<int:pk>/detail', views.PartyDetailView.as_view(), name='party_detail'),
    path('parties/create/',login_required(views.PartyCreateView.as_view()), name='party_create'),
    path('parties/<int:pk>/update/',login_required(views.PartyUpdateView.as_view()), name='party_update'),
    path('parties/<int:pk>/delete/',login_required(views.PartyDeleteView.as_view()), name='party_delete'),
     #politician    
     path('politicians/',views.PoliticianListView.as_view(), name='politicians'),
    path('politicians/<int:pk>/detail',views.PoliticianDetailView.as_view(), name='politician_detail'),
    path('politicians/create/',login_required(views.PoliticianCreateView.as_view()), name='politician_create'),
    path('politicians/<int:pk>/update/',login_required(views.PoliticianUpdateView.as_view()), name='politician_update'),
    path('politicians/<int:pk>/delete/',login_required(views.PoliticianDeleteView.as_view()), name='politician_delete'),     
    #evidences    
     path('evidences/',login_required(views.EvidenceListView.as_view()), name='evidences'),
    path('evidences/<int:pk>/detail',views.EvidenceDetailView.as_view(), name='evidence_detail'),
    path('evidences/create/',login_required(views.EvidenceCreateView.as_view()), name='evidence_create'),
    path('evidences/<int:pk>/update/',login_required(views.EvidenceUpdateView.as_view()), name='evidence_update'),
    path('evidences/<int:pk>/delete/',login_required(views.EvidenceDeleteView.as_view()), name='evidence_delete'),  
    # API
    path("api/", include(("promise_tracker.routers", "api"), namespace="api")),    
]+ static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

promise_tracker/models.py
# from statistics import mode
from email.policy import default
from random import choices
from statistics import mode
from unittest.util import _MAX_LENGTH
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
# from numpy import blackman
from django_countries.fields import CountryField

class BaseModel(models.Model):
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
 
    class Meta:
        abstract = True

class User(AbstractUser, BaseModel):
    is_anonymous = models.BooleanField(default=True)
    def __str__(self):
        return self.username
    @property
    def get_user(self):
        if self.is_anonymous:
            return "anonymous"
        else:
            return self.username


class Position(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Party(models.Model):
    name = models.CharField(max_length=64, blank=False, null=False)
    logo = models.ImageField(null=True, blank=True, upload_to='parties/')
    acronym = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.acronym + " - " + self.name

    class Meta:
        verbose_name = "Party"
        verbose_name_plural = "Parties"    



class Politician(models.Model):
    PRIMARIA = '01'
    SECUNDARIA = '02'
    UNIVERSITARIO = '03'
    MAESTRIA = '04'
    DOCTORADO = '05'
    EDUCATION_CHOICES = [
        (PRIMARIA, 'Primaria'),
        (SECUNDARIA, 'Secundaria'),
        (UNIVERSITARIO, 'Universitario'),
        (MAESTRIA, 'Maestria'),
        (DOCTORADO, 'Doctorado'),
    ]
    fname = models.CharField(max_length=64)
    lname = models.CharField(max_length=64)
    party = models.ForeignKey(Party, on_delete=models.CASCADE, related_name='parties', null=True)
    country = CountryField()
    religion = models.CharField(max_length=64, blank=True)
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, related_name="positions")
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    education = models.CharField(
        max_length=2,
        choices=EDUCATION_CHOICES,
        default=PRIMARIA,
    )
    photo = models.ImageField(null=True, blank=True, upload_to='politician/')
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.fname} {self.lname}"
    @property
    def promise_count(self):
        return self.politician_promises.all().count()


class PartyValidity(models.Model):
    politician = models.ForeignKey(
        Politician, on_delete=models.CASCADE, null=True)
    party = models.ForeignKey(
        Party, on_delete=models.CASCADE, null=True, blank=True)
    ini = models.DateField()
    end = models.DateField()

class Rating(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    color = models.CharField(max_length=6)
    order = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.title}"
    class Meta:
        ordering = ['order']

class Source(models.Model):
    NEWS = '01'
    VIDEO = '02'
    PHOTO = '03'
    TYPES_CHOICES = [
        (NEWS, 'Prensa'),
        (VIDEO, 'Video'),
        (PHOTO, 'Foto'),
    ]
    url = models.CharField(max_length=200)
    type = models.CharField(max_length=2,
                            choices=TYPES_CHOICES,
                            default=PHOTO)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{ self.TYPES_CHOICES[0][int(self.type)] }:: {self.url}"


class Promise(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_kpi = models.FloatField()
    rating = models.ForeignKey(
        Rating, related_name="ratings", on_delete=models.CASCADE)
    # fuentes = models.ManyToManyField(Source, related_name="promise_sources", default=None, blank=True)
    politician = models.ForeignKey(Politician, related_name="politician_promises", on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} :: {self.rating.title}" 
    @property
    def evidence_count(self):
        return self.evidences.all().count()


class Evidence(models.Model):
    title = models.CharField(max_length=200)
    source = models.CharField(max_length=200, default='')
    # fuentes = models.ManyToManyField(Source, related_name="evidense_sources")
    promise = models.ForeignKey(
        Promise, on_delete=models.CASCADE, related_name="evidences")
    kpi = models.FloatField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=False)

promise_tracker/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Promise, Evidence, Party, Position, Politician, Source, User, PartyValidity, Rating

class PromisesForm(forms.ModelForm):
    title = forms.CharField(label='Title:', max_length=200, widget=forms.TextInput(
                              attrs={'class': 'form-control'}))
    description = forms.CharField(label='Description:', widget=forms.Textarea(
                              attrs={'class': "form-control"}))                           
    politician = forms.ModelChoiceField(label='Politician:', widget=forms.Select(attrs={'class': "form-control"}), queryset=Politician.objects.filter(status=True))  
    start_kpi = forms.CharField(label='Key performance indicator (KPI):', widget=forms.TextInput(attrs={'class': "form-control"}))                              
    rating = forms.ModelChoiceField(label='Rating:', widget=forms.Select(attrs={'class': "form-control"}),queryset=Rating.objects.all())
    
    class Meta:
        model = Promise
        fields = ['title','description', 'politician', 'start_kpi', 'rating']
        # widget = {
        # 'title': forms.TextInput(attrs={'class':'form-control'}),
        # }

    # fuentes = models.ManyToManyField(Source, related_name="promise_sources")
    # creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, default=None)
    # date = models.DateField(auto_now_add=True)
    # status = models.BooleanField(default=False)
class EvidenceForm(forms.ModelForm):    
    title = forms.CharField(label='Title:', max_length=200, widget=forms.TextInput(
                              attrs={'class': 'form-control'}))
    source = forms.CharField(label='Source:', max_length=200, widget=forms.TextInput(
                              attrs={'class': 'form-control'}))                              
    kpi = forms.CharField(label='Key performance indicator (KPI):', widget=forms.TextInput(attrs={'class': "form-control"}))                              
    class Meta:
        model = Evidence
        fields = ['title', 'source', 'kpi']

promise_tracker/templates/party/party_confirm_delete.html
{% extends "promise_tracker/layout.html" %}
{% load static %}

{% block body %}
{% url 'parties' as party_list %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Position</h1>

        <p class="h5">Are you sure you want to delete the party?</p>
        <h3 class="my-5">{{ party }}</h3>
        <form method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'parties' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{party_list}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

promise_tracker/templates/party/party_detail.html
{% extends "promise_tracker/layout.html" %}
{% load static %}

{% block body %}
<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Party Details</h1>
        <div class="d-flex justify-content-center">            
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                {% if party.get_fields|length > 1 %}
                    {% for label, value in party.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                <tr>
                    <td> {% if party.logo %}<img src="{{party.logo.url}}" /> {% endif %}</td>
                    <td>Name</td>
                    <td>{{party.name}}</td>                    
                </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'parties' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

promise_tracker/templates/party/party_form.html
{% extends "promise_tracker/layout.html" %}
{% load static %}

{% block body %}
    <h1>New Party </h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            <input type="submit" value="Save">
        </div>
    </form>

promise_tracker/templates/party/party_list.html
{% extends "promise_tracker/layout.html" %}
{% load static %}

{% block body %}
    <h1>Parties </h1>
    <ul>
    {% for party in party_list %}
                <li>
                    <span>{{ party }}</span>
                    <a href="{% url 'party_detail' party.id %} ">View</a>
                    <a href="{% url 'party_update' party.id %} ">Update</a>
                    <a href="{% url 'party_delete' party.id %}">Delete</a>
                </li>
    {% endfor %}    
    </ul>    
{% endblock %}